#!/usr/bin/python3
from sys import argv

domain = argv[1]

print('-' * 100)
print("Google Dorks")
print(f"site:{domain} intext:\"access_token\"")
print(f"site:{domain} intext:\"access_token\" -site:cloud.*")
print(f"site:{domain} intext:\"access_token\" -inurl:cloud")
print(f"site:{domain} intitle:\"index of\"")
print(f"site:{domain} intitle:\"index of\" intext:\"passwd\"")
print(f"site:{domain} intext:\"id_rsa\" -inurl:cloud|mirror AND intitle:\"index of\"")
print(f"site:{domain} AND intext:'**one_of_password_pattern_value_here**'")
print(f"\"Org:{domain}\": NPM_API_KEY=")
print(f"\"Org:{domain}\": NPM_API_TOKEN=")
print(f"\"Org:{domain}\": NPM_AUTH_TOKEN=")
print(f"\"Org:{domain}\": NPM_CONFIG_AUDIT=")
print(f"\"Org:{domain}\": NPM_CONFIG_STRICT_SSL=")
print(f"\"Org:{domain}\": NPM_EMAIL=")
print(f"\"Org:{domain}\": NPM_PASSWORD=")
print(f"\"Org:{domain}\": ")
print(f"\"Org:{domain}\": NPM_SECRET_KEY=")
print(f"org:{domain} ftp")
print(f"org:{domain} Ldap")
print(f"org:{domain} https://")
print(f"org:{domain} language:python .php")


print(f"site:{domain} -www -shop -share -ir -mfa")

# Pastebin Leaks
print(f"site:pastebin.com \"{domain}\"")
print(f"site:jsfiddle.net \"{domain}\"")
print(f"site:codebeautify.org \"{domain}\"")
print(f"site:codepen.io \"{domain}\"")


# PHP extension w/ parameters
print(f"site:{domain} ext:php inurl:?")

# Disclosed XSS and Open Redirect Bug Bounties
print(f"site:openbugbounty.org inurl:reports intext:\"{domain}\"")

print(f"(site:{domain} | site:{domain}) & \"choose file\"")

print(f"site:{domain} \"index of\" inurl:ftp secret")

print(f"site:{domain} inurl:'/content/dam'")


print('-' * 100)
print("Shodan Dorks")
print(f"ssl.cert.subject.cn:\"{domain}\" http.title:\"admin\"")
print(f"ssl: \"{domain}\" http.title: \"admin\"")
print(f"ssl.cert.subject.cn:\"{domain}\" admin")
print(f"ssl: \"{domain}\" admin")

print(f'http.html:"Wordpress" org:{domain}')
print(f'http.html:"Discourse" org:{domain}')
print(f'http.html:"Grafana" org:{domain}')
print(f'http.html:"Jenkins" org:{domain}')
print(f'http.html:"MongoDB" org:{domain}')
print(f'http.html:"JBoss" org:{domain}')
print(f'http.html:"Drupal" org:{domain}')
print(f'http.html:"Joomla" org:{domain}')
print(f'http.html:"Kibana" org:{domain}')
print(f'http.html:"Elastic" org:{domain}')
print(f'http.html:"Elasticsearch" org:{domain}')
print(f'http.html:"Docker"  org:{domain}')
print(f'http.html:"Kubernetes" org:{domain}')
print(f'http.html:"Redis" org:{domain}')
print(f'http.html:"Citrix" org:{domain}')
print(f'http.html:"Outlook" org:{domain}')
print(f'http.html:"Owa" org:{domain}')
print(f'http.html:"Index of /" org:{domain}')
print(f'http.html:"DisallowedHost at /" org:{domain}')
print(f'http.html:"InfluxDB" org:{domain}')
print(f'http.html:"Apache Kafka" org:{domain}')
print(f'http.html:"Apache Tomcat" org:{domain}')
print(f'http.html:"Prometheus" org:{domain}')
print(f'http.html:"Logstash" org:{domain}')
print(f'http.html:"Terraform" org:{domain}')
print(f'http.html:"Jira" org:{domain}')
print(f'http.html:"Atlassian" org:{domain}')
print(f'http.html:"Confluence" org:{domain}')
print(f'http.html:"GraphQL" org:{domain}')
print(f'http.html:"Gitlab" org:{domain}')
print(f'http.html:"Git" org:{domain}')
print(f'http.html:"Github" org:{domain}')
print(f'http.html:"Postman" org:{domain}')
print(f'http.html:"Swagger UI" org:{domain}')
print(f'http.html:"nagios" org:{domain}')


print(f'port:21 "proftpd" org:{domain}')
print(f'port:21 "220" "230 Login successful." org:{domain}')
print(f'port:27017 "MongoDB Server Information" org:{domain}')
print(f'port:22 OpenSSH org:{domain}')
print(f'port:25 "exim" org:{domain}')
print(f'port:80 "Apache httpd" org:{domain}')
print(f'port:3389 "remote desktop" org:{domain}')
print(f'product:"Apache httpd" org:{domain}')
print(f'product:"OpenSSH" org:{domain}')
print(f'product:"ciscoSystems" org:{domain}')
print(f'product:"nginx" org:{domain}')
print(f'product:"BigIP" org:{domain}')
print(f'product:"Microsoft HTTPAPI httpd" org:{domain}')
print(f'product:"Apache Tomcat/Coyote JSP engine" org:{domain}')
print(f'product:"OpenResty" org:{domain}')
print(f'product:"Postfix smtpd" org:{domain}')
print(f'product:"MySQL" org:{domain}')
print(f'product:"Exim smtpd" org:{domain}')
print(f'product:"Kubernetes" org:{domain}')
print(f'product:"AkamaiGHost" org:{domain}')
print(f'product:"PostgreSQL" org:{domain}')
print(f'product:"MiniServ" org:{domain}')
print(f'product:"Grafana (Open Source)" org:{domain}')
print(f'product:"SQL Server Browser Service" org:{domain}')
print(f'product:"Apache Tomcat" org:{domain}')
print(f'product:"Node.js" org:{domain}')
print(f'product:"CouchDB" org:{domain}')
print(f'product:"MongoDB" org:{domain}')
print(f'product:"Memcached" org:{domain}')
print(f'http.html:"Wordpress" org:{domain}')
print(f'http.html:"Discourse" org:{domain}')
print(f'http.html:"Grafana" org:{domain}')
print(f'http.html:"Jenkins" org:{domain}')
print(f'http.html:"MongoDB" org:{domain}')
print(f'http.html:"JBoss" org:{domain}')
print(f'http.html:"Drupal" org:{domain}')
print(f'http.html:"Joomla" org:{domain}')
print(f'http.html:"Kibana" org:{domain}')
print(f'http.html:"Elastic" org:{domain}')
print(f'http.html:"Elasticsearch" org:{domain}')
print(f'http.html:"Docker"  org:{domain}')
print(f'http.html:"Kubernetes" org:{domain}')
print(f'http.html:"Redis" org:{domain}')
print(f'http.html:"Citrix" org:{domain}')
print(f'http.html:"Outlook" org:{domain}')
print(f'http.html:"Owa" org:{domain}')
print(f'http.html:"Index of /" org:{domain}')
print(f'http.html:"DisallowedHost at /" org:{domain}')
print(f'http.html:"InfluxDB" org:{domain}')
print(f'http.html:"Apache Kafka" org:{domain}')
print(f'http.html:"Apache Tomcat" org:{domain}')
print(f'http.html:"Prometheus" org:{domain}')
print(f'http.html:"Logstash" org:{domain}')
print(f'http.html:"Terraform" org:{domain}')
print(f'http.html:"Jira" org:{domain}')
print(f'http.html:"Atlassian" org:{domain}')
print(f'http.html:"Confluence" org:{domain}')
print(f'http.html:"GraphQL" org:{domain}')
print(f'http.html:"Gitlab" org:{domain}')
print(f'http.html:"Git" org:{domain}')
print(f'http.html:"Github" org:{domain}')
print(f'http.html:"Postman" org:{domain}')
print(f'http.html:"Swagger UI" org:{domain}')
print(f'http.html:"nagios" org:{domain}')